### ISSUE TITLE
loads works with single quote string and not with double quote one.

### ISSUE THREAD

**Issue by vnitinv** [skorokithakis/jsane#6]
``` python
>>> jsane.loads('{"junos": "normal"}')
<Traversable: {u'junos': u'normal'}>
>>> jsane.loads("{'junos': 'normal'}")

Traceback (most recent call last):
  File "<pyshell#37>", line 1, in <module>
    jsane.loads("{'junos': 'normal'}")
  File "/Library/Python/2.7/site-packages/jsane/wrapper.py", line 12, in loads
    j = json.loads(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 1 column 2 (char 1)
```

**Comment by skorokithakis** [comment]
Yes, single quotes are invalid JSON.
